In [1]:
import numpy as np

In [3]:
values = [23, 19, 34, 50]

In [5]:
np_values = np.array(values)
print(np_values)

[23 19 34 50]


In [13]:
x = np.arange(12,36)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]


In [17]:
x2 = np.arange(10,19,2)
print(x2)

[10 12 14 16 18]


In [19]:
x3 = np.arange(8,-4,-1)
print(x3)

[ 8  7  6  5  4  3  2  1  0 -1 -2 -3]


In [21]:
mpg = np.array([19, 23, 20, 21, 20, 23, 21, 21, 23, 19, 24, 23, 28, 19, 18, 21, 23, 17, 20, 20, 20, 21, 24, 18, 15])

In [23]:
print(mpg[3:10])

[21 20 23 21 21 23 19]


In [27]:
print(mpg[15:])

[21 23 17 20 20 20 21 24 18 15]


In [43]:
goodMpg = mpg[mpg >= 23]
print(goodMpg)

[23 23 23 24 23 28 23 24]


In [69]:

okMpg = mpg[(mpg > 18) & (mpg < 23)]
print(okMpg)

[19 20 21 20 21 21 19 19 21 20 20 20 21]
[19 20 21 20 21 21 19 19 21 20 20 20 21]


In [71]:
kpl = mpg * 0.425
print(kpl)

[ 8.075  9.775  8.5    8.925  8.5    9.775  8.925  8.925  9.775  8.075
 10.2    9.775 11.9    8.075  7.65   8.925  9.775  7.225  8.5    8.5
  8.5    8.925 10.2    7.65   6.375]


In [79]:
A = np.arange(2,11).reshape(3,3)
print(A)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [83]:
A[(A > 3) & (A<7)] = -A[(A > 3) & (A < 7)]
print(A)

[[ 2  3 -4]
 [-5 -6  7]
 [ 8  9 10]]


In [87]:
print(A[0])

[ 2  3 -4]


In [95]:
print(A[:,2].reshape(3,1))

[[-4]
 [ 7]
 [10]]


In [99]:
print(np.sum(A[:,1]))

6


In [107]:
print(np.mean(A)) # prints average in mean

2.6666666666666665


In [113]:
print(np.median(A[:,1]))

3.0


In [115]:
row = np.array([-2,1,2])
result = A + row
print(result)

[[ 0  4 -2]
 [-7 -5  9]
 [ 6 10 12]]


In [123]:
B = np.arange(24).reshape(4,3,2)
print(B)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
